 #### Name: Bushra Hossain
 ####  Intern ID : i23b0034s26
 


Problem 1

In [ ]:
import numpy as np

In [4]:
import numpy as np
a = np.array([[1,2,3],

              [4,5,6],
             [2,3,4]])

 
b = np.array([[10,11,12],
             [13,14,15],
             [2,3,4]])

 
c = a + b

print(c)

a


[[11 13 15]
 [17 19 21]
 [ 4  6  8]]


array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

PROBLEM 2

In [8]:
import numpy as np

a = np.array([[[1, 2],
            [2, 4],
            [3, 6]]])


5*a

array([[[ 5, 10],
        [10, 20],
        [15, 30]]])

PROBLEM 3


In [10]:
i = np.eye(10)

i*5

array([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

###### Problem 4: Create a 1-Dimensional array with 20 elements starting from  100 with an increment 5. Convert the array to a 3-Dimensional array 3da and display.



In [34]:
s = [x for x in range(100, 196, 5)]


In [33]:
s2=np.array(s)
s3=s2.reshape(2,2,5)
s3

array([[[100, 105, 110, 115, 120],
        [125, 130, 135, 140, 145]],

       [[150, 155, 160, 165, 170],
        [175, 180, 185, 190, 195]]])

Problem 5: Define a and b as 2-D arrays with 4 elements and merge the arrays horizontally as m and display.



In [35]:
a1 = np.array([[1,2,3],
              [4,5,6],
              [2,2,2],
              [3,1,2]])

 
a2 = np.array([[7,8,9],
             [10,11,12],
               [1,2,3],
               [2,3,4]])

 
m= np.hstack((a1, a2))
m


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12],
       [ 2,  2,  2,  1,  2,  3],
       [ 3,  1,  2,  2,  3,  4]])

Problem 6: Define a and b as 2-D arrays with 4 elements and merge the arrays vertically as mv and display.



In [36]:
a1 = np.array([[1,2,3],
              [4,5,6],
              [2,2,2],
              [3,1,2]])

 
a2 = np.array([[7,8,9],
             [10,11,12],
               [1,2,3],
               [2,3,4]])

 
mv= np.vstack((a1, a2))

mv


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 2,  2,  2],
       [ 3,  1,  2],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 2,  3,  4]])